services: 
  control:
    container_name: control
  # https://docs.docker.com/compose/compose-file/build/
    build: 
      context: ./env
      dockerfile: Dockerfile-control
    hostname: control
    links:
      - amh1
      - amh2
    ports:
      - "2200:22"
    volumes:
      - ./ansible:/home/ansible/ansible
    tty: true
    stdin_open: true
    # command: bash
    networks:
      - build-network
  amh1:
    container_name: amh1
    build: ./env
    hostname: amh1
    ports:
      - "2201:22"
    networks:
      - build-network
  amh2:
    container_name: amh2
    build: ./env
    hostname: amh2
    ports:
      - "2211:22"
    networks:
      - build-network
networks:
    build-network:
        driver: bridge