services: 
  control:
    container_name: control
  # https://docs.docker.com/compose/compose-file/build/
    build: 
      context: ./env
      dockerfile: Dockerfile-control
    hostname: control
    links:
      - lb
      - web1
      - web2
    ports:
      - "2200:22"
    volumes:
      - ./ansible:/home/ansible/ansible
    tty: true
    stdin_open: true
    command: bash
    networks:
      - build-network    
  lb:
    container_name: lb
    build: ./env
    hostname: lb
    links:
      - web1
      - web2
    ports:
      - "2201:22"
      - "8001:80"
    networks:
      - build-network
  web1:
    container_name: web1
    build: ./env
    hostname: web1
    ports:
      - "2211:22"
      - "8081:80"
    networks:
      - build-network
  web2:
    container_name: web2
    build: ./env
    hostname: web2
    ports:
      - "2212:22"
      - "8082:80"
    networks:
      - build-network
networks:
    build-network:
        driver: bridge