FROM alpine:latest

# Add certs to the container to access internal urls
# COPY RBSGlobalG1RootCA.crt /var/tmp
# COPY RBSGlobalG1IssuingCA.crt /var/tmp


RUN apk add --no-cache --update wget ca-certificates unzip python3 py3-pip openssl bash curl openssh sudo git tzdata jq coreutils openssh-server && \
apk --no-cache --update add --virtual build-dependencies python3-dev libffi-dev openssl-dev build-base cairo-dev cargo freetype-dev rust && \
pip --no-cache install --upgrade pip cffi && \
pip --no-cache install ansible && \
pip --no-cache install ansible-lint && \
pip --no-cache install molecule  && \
pip --no-cache install yaml-checker  && \
pip --no-cache install lxml  && \
apk del build-dependencies && \
# regress the ssh_config client to work with older versions of sshd 
echo -e "Host * \HostkeyAlgorithms +ssh-rsa \n PubkeyAcceptedAlgorithms +ssh-rsa" >> /etc/ssh/ssh_config && \
# cp /var/tmp/RBSGlobalG1RootCA.crt /usr/local/share/ca-certificates && \
# update-ca-certificates && \
# cp /var/tmp/RBSGlobalG1IssuingCA.crt /usr/local/share/ca-certificates && \
# update-ca-certificates && \
rm -rf /var/cache/apk/* && \
mkdir -p /home/ansible/.ssh/ && \
  chmod 0700 /home/ansible/.ssh/

COPY ssh_config /home/ansible/.ssh/config
COPY ansible /home/ansible/.ssh/id_rsa
COPY ansible.pub /home/ansible/.ssh/id_rsa.pub
COPY ansible.pub /home/ansible/.ssh/authorized_keys

# CMD ["tail", "-f", "/dev/null"]

CMD ["bash"]